### ISSUE TITLE
[Epic] Galleries gridview and other gallery enhancements

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#123]
This enhancement proposes to broaden the scope of galleries to include all images contained within Stash Library folders. To display the gallery in a card grid-view (exactly as scenes are displayed). To let users assign metadata to images, to create [sets](#sets), and to assign images or sets to scenes.

**Contents**
1. [UI UX](#UI%20UX)
2. [Full-screen mode](#full-screen%20mode)
3. [Sets](#Sets)
4. [Mass tagging](#mass%20tagging)
5. [Editing & Metadata](#editing%20&metadata)
6. [Filter container](#filter%20container)

# UI UX
For UI UX consistency with the rest of Stash the galleries section would look and behave the same way as the scenes card grid view card. This includes:

- [x] Filter container at the top of the page
- [x] Image thumbnails should be displayed as cards, like scene card gird view
- [x] Metadata associated with each image: `title`, `performers`, `tags`, `scene relationship`, `set relationship`, `studio/channel`, `date`, and `url`
- [x] Clicking an image enters a [full-screen mode](#full-screen%20mode)

Because image galleries could be massive, I think it is imperative to optimize space and keep a simple design in card grid view with. Metadata isn't that relevant for galleries in card view but can still be displayed with overlays:
- [x] Do not display any metadata placeholders unless it exists!
- [x] If a title exists it should be displayed an overlay (z-index) on the image thumbnail.
- [x] If other metadata exists it should be displayed as an overlay with [icon indicators](https://blueprintjs.com/docs/#core/components/icon). On mouseover of icon indicator a tool tip will show the metadata values.

# Full-screen mode
Clicking an image in card view would not redirect to a new page, rather it would display the image as an [overlay](https://blueprintjs.com/docs/#core/components/overlay).
- [x] The image would be displayed to its largest possible dimensions within the viewport of the browser window.
- [x] Left and right chevrons would let the user scroll through the image gallery while remaining in full-screen mode. Left chevron = prior image, right chevron = next image
- [ ] Add ability to swipe left or right for mobile/touch viewports #2857 #2538
- [x] A narrow footer on the bottom of the viewport can display metadata such as title, performer, etc
- [x] Exiting full-screen mode via `<esc>` keypress or a mouse press anywhere on the image that's not the left/right navigation chevrons

![64834187-dbca3a00-d5ae-11e9-8bd6-4d3bd9b19b96](https://user-images.githubusercontent.com/37937507/91379092-df6ec500-e7ef-11ea-85b7-12bfd60ddcdb.png)

# Sets
Sets would be a group of images that share a user-defined relationship. An example of a set would be two or more images belonging to the same photo shoot or scene.

- ~~Sets can be displayed by toggling a `set` button in the filter container. It toggles between sets card view and the default gallery card view.~~
- ~~Sets should be represented by a thumbnail in a card view~~
- [x] Clicking a set displays a card view of all the images within the set
- [x] By default the first image in the set can be the primary image that represents the set in card view.
- [ ] ~~Using Blueprint's~~ right click functionality; we can right click an image within the set to set it as the primary image
- [x] A set should be automatically created if more than one image is assigned to the same scene

# Mass tagging
- [x] @WithoutPants has already implemented mass tagging. This could be extended to a galleries list view.

# Editing & Metadata
The typical Stash convention is that clicking an object from the card view page navigates towards a new page with a panel for editing metadata. Galleries would break that convention with full-screen mode. There needs to be an optional way to edit image metadata and other image parameters:
- [x] On image card mouseover display an edit icon. Click the icon navigates to the conventional Stash edit/file info panel page where the user can modify metadata:
- title: title of image
- performer: list of performers associated with image
- date: yyyy-mm-dd
- tags: any stash tags associated with image
- channel/studio: associate channel/studio to image
- url: specify a url for image
- sets: associate image with a set (of other images) or create new set
- delete image
- [x] scene: user can associate the image to a scene
- [x] Delete image from library and delete file as per scene deletion behavior

# Filter container
- [x] Add images and collections to the filter container

**Updated**: Clarified several headings

**Comment by echo6ix** [comment]
I'm closing this issue. Every task has more-or-less been addressed except for swiping in lightbox, and there's two open issues addressing that.
