### ISSUE TITLE
[EPIC] A robust tagging and metadata collection and curation system.

### ISSUE THREAD

**Issue by Leopere** [stashapp/stash#155]
It would be excellent to have something that matches functionality for tagging file renaming and metadata curation of the Music focused Picard by MusicBrainz.

We should have a system where the goal is to gather metadata and help curate this type of content it could even go so far as to help index indie content or even help people recognize and eliminate bad or illegal content from their collections easier.

It would be awesome to use FFMPEG's Perceptual Fingerprinting to determine the visual accuracy to the source lossless or at least original quality content.  

## Goals
* [] Determine the Perceptual Fingerprint of a file efficiently.
* [] Scrape for metadata from within the filename, folder structure, embedded file tag data.
* [] Check a central DB for metadata against what was discovered locally if the data is not stored notify the operator of Stash that the data could be contributed to the central DB.
* [] Verify data submitted through crowdsourcing so the more people who submit similar tags or missing tags the more confident the database can present the records as to the end-user.
* [] Write a CLA that would be applied to data contributors that will disclaim that contributors are responsible for the data they submit to the database.
* [] Invent some way to determine what is good source data vs what is lossy transcodes.

**Comment by ueaslsef** [comment]
ideo-Entries have an url attribute. This is a good identifier for a video and could be used to link multiple versions (quality, formatting) of a video together.

What could also be done would be scene scrapers, like the actor scraper that already exists.

**Comment by Leopere** [comment]
@ueaslsef you thinking about something like a UUID based on the fingerprint of the content?

**Comment by tritnaha** [comment]
Something like theporndb (https://theporndb.herokuapp.com/api/scenes/) or jsonporn could fill this void to some extent.

**Comment by WithoutPants** [comment]
Covered by stash-box.
