### ISSUE TITLE
[RFC] Make Stash more suitable for JAV

### ISSUE THREAD

**Issue by YurikaL** [stashapp/stash#3065]
Stash data schema doesn't cover all JAV-related metadata. So it's worth improving it!

##  Long Form

There is a some specific suggestions to improve JAV support:

* [ ] New field: Code. JAV movies are unambiguously (well, _almost_ unambiguously) identified by it's DVD code. May be suitable for some non-JAV studios as well. Related issues: #2607
* [ ] New field: Label. JAV movies have separate Maker and Label studio fields, but currently Stash allows to assign only one studio to scene. The solution could also be to assign multiple arbitrary studios to scenes, but with custom or semi-custom comment. This could be useful for Western as well, since some Western scenes are re-released by multiple publishers with no changes (maybe except watermark), which has no representation in Stash.
* [ ] New feature: Series. JAV movies are often organized by series, but currently there is no way to properly represent this in Stash. Related issues:  #723  #605 #1352 #1402 #2821 (also  #728)
* [ ] Create movies from scenes  / add new type of relationship between scene and movie: "scene IS movie" / allow scraping directly to movies in scraping view / auto-display or auto-copy scenes metadata into related movies / or even deeply rework Movies at all. JAV scenes are almost always equals to movies, scenes are almost never released separately, so it would be useful to share more relationship with these types. Related issues: #728
* [ ] Handle multi-part scenes.  #2276
* [ ] New feature: Multi-language support for all relevant fields: Titles, Descriptions, Performer names. Besides Latin transliteration, it is worth storing and displaying original Japanese titles and names (and maybe translations into other languages).
* [ ] Match performer aliases when scrapping. Probably much easier to implement if the following suggestion will also be implemented.
* [ ] Rework Performer aliases. Ability to add a separate field for each performer's alias, also with multilanguage support. E.g., Japanese name and all variants of it's Latin transliteration variants should be treated as fields of one alias. Related issues: #422
* [ ] New feature: Performer Name order. Currently performer names are stores as it comes from scrapers, but it would be nice to switch between Japanese or Western name order on the fly in transliterated performer aliases.
* [ ] Abitily to add multiple URLs to scenes, movies and performers (and maybe native multiscraping feature?) Often there are multiple urls containing information about JAV movie and JAV performers: pages from various stores, various database pages... It's worth storing (and maybe scraping) them all! #703
* [ ] Maybe auto-crop poster if it matches a certain aspect ratio? JAV covers are almost always a double-sided DVD covers, but Stash UI seems like to adjusted to display a vertical front cover.
* Maybe something else..?

## Examples

<details><summary>Jellyfin JAV plugin allow to change performer name order</summary>

![Jellyfin JAV plugin settings](https://user-images.githubusercontent.com/43180936/199321967-4d041a55-7bc8-4afa-b8ca-9e08c1e5f5f0.png)
https://github.com/imaginary-upside/JellyfinJav/

</details>

## Reference Reading

https://en.wikipedia.org/wiki/Pornography_in_Japan#Video_(JAV)
https://en.wikipedia.org/wiki/Japanese_name

**Comment by WeedLordVegeta420** [comment]
I might give some more detailed feedback on this list later, but for now I'll just add that several of these are already handled on stash-box, and would be covered by aligning stash with the same metadata features - see #2359 

#3051 addresses the addition of the `Code` field, as well as `Director` which is also very relevant in JAV.

**Comment by DogmaDragon** [comment]
There is PR for studio code https://github.com/stashapp/stash/pull/3051

Series/movies/parts will probably be handled by some kind of grouping system that has been talked a lot about in Discord. v0.17 `files-refactor` was a big step towards this goal since now Stash can link multiple files to a single entry. It's a huge task since it needs to be done on both the Stash and stash-box end to not break functionality to submit information.

**Comment by YurikaL** [comment]
Thanks for the feedback, issue updated! Looking forward for grouping system implementation and other things.

> as well as Director which is also very relevant in JAV.

Displaying `Director` from linked movies was originally implied in the suggestion about scenes and movies relationship, and now it's also a separate suggestion.

**Comment by YurikaL** [comment]
Update: 

- add link to [another](https://github.com/stashapp/stash/issues/3201) series-related feature request;
- add links to some JAV movie series to Examples section.

**Comment by YurikaL** [comment]
Update:
- add issue about Performer aliases: #3224;
- Implement in advance [Label scraping](https://github.com/stashapp/CommunityScrapers/pull/1190/commits/c90eac40726186960c4b6ea34c503b15bc5ab6b5) and [Performers name order](https://github.com/stashapp/CommunityScrapers/pull/1190/commits/5da3dd513f2df7411e2f5621d92421214516d153) in JavLibrary_python community scraper.

**Comment by neru2132** [comment]
Aliases for directors would also be very nice, mainly for the original name and different (mis)romanizations.

There are also a couple of instances where former performers turned directors. It could be nice to be able to link them in some way, but this part is not too important I would say.
