### ISSUE TITLE
[Feature] Better Production containers for a stable release.

### ISSUE THREAD

**Issue by Leopere** [stashapp/stash#353]
**Is your feature request related to a problem? Please describe.**
* [x] Multi Stage Docker builds
* [ ] Every version of the Docker containers should be compile from source so people can take any commit from Version 0.1.0 forward and have all of the tools required to produce binaries for testing locally. 
* [ ] Documentation for Development
* [ ] Security updates to [user privileges](https://github.com/stashapp/stash/blob/develop/docker/production/x86_64/Dockerfile#L20-L23) of the production container.  This may benefit from a permissions assertion binary that asserts permissions for specific folders for the container on container run.  [Docker run lines for a perms assertion app](https://github.com/lbryio/lbry-docker/blob/fced92808905e6c23110d01c63df38d07290d5e2/lbrycrd/Dockerfile-linux-x86_64-production#L4-L16) [c binary for asserting perms in a static directory path](https://github.com/lbryio/lbry-docker/blob/fced92808905e6c23110d01c63df38d07290d5e2/lbrycrd/stuff/fix-permissions.c) this is how it's [invoked](https://github.com/lbryio/lbry-docker/blob/fced92808905e6c23110d01c63df38d07290d5e2/lbrycrd/stuff/start.sh#L52-L53)
* [ ] Production and Dev containers need reworked totally.

**Describe the solution you'd like**
I would like to have some time to write this and test a multi-stage build Dockerfile for production and dev that basically both do the same thing.  Perhaps pulls the compiler image from the upstream but have the option to pull a local one.

**Describe alternatives you've considered**
Open to suggestions. 

**Additional context**
I would like to keep transparency as best as possible everywhere so logs being where people expect them and keep the technical debt down to avoid maintenance hell.

Blocks #339

**Comment by WithoutPants** [comment]
By having the docker container compile from source, we run the risk of inconsistencies between the packaged versions and the docker compiled versions. Having the docker container get the release via curl guarantees that they are consistent. For the end user stable and development versions, these should maintain this imo.

At the moment we only have a single "production" docker file which (incorrectly) grabs the latest development build currently. This should be changed to get the latest stable, and a new "development" docker file created which gets the latest development release.

The current production docker file is already multi-staged, so I'm not sure how much further we can and want to divide it further.

> Every version of the Docker containers should be compile from source so people can take any commit from Version 0.1.0 forward and have all of the tools required to produce binaries for testing locally.

I'm still trying to get my head around what you mean by this. An off-the-top-of-my-head alternative is to create an additional "compiled" docker file that grabs a specific commit (provided as a build argument) from github, and compiles it producing a (presumably?) linux binary.

**Comment by Leopere** [comment]
I would like it to be possible for someone to cherrypick any commit from the git tree locally from version 0.1.0 forward and be able to run scripts locally to be able to produce a build from the version they picked.

I suppose there could be a scenario or two where one build has one dependency and 10 minutes later a new dependency upstream has a release and then the docker hub queues something up that's newer I guess it seems almost as probably as that edge case I mentioned earlier.  I don't think that it is a concern.

Currently, the production container is not multi-staged.  It has multiple layers but it's not multi-staged.  You can have multiple stages that are built on different base images.  We must be talking about different Dockerfiles because [this one](https://github.com/stashapp/stash/blob/master/docker/production/x86_64/Dockerfile) isn't multi-stage nor is the one in the develop branch.

**Comment by WithoutPants** [comment]
From the dockerfile you linked:
```
# stage 1
FROM ubuntu:18.04 as prep
...snip...

# stage 2
FROM ubuntu:18.04 as app
...snip...
COPY --from=prep /stash /ffmpeg/ffmpeg /ffmpeg/ffprobe /usr/bin/
```

How would you further stage this?

Regarding building a particular release: I can see the benefit of this, but I think it belongs in a separate docker file. It is unfortunately another place that we have to maintain the build scripts (adding to `.travis.yml`, `cross-compile.sh` and the make file), but I think we can live with that.

So to summarise, my suggestions: 
- change the production dockerfile to curl from the latest full release rather than the development release
- add a development dockerfile which is the same as the production one, but curls from the latest development release instead
- create a new multi-stage docker file that follows the build process to produce a docker container of the current source tree
